apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx

---
apiVersion: v1
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: emqx
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","watch","list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: emqx
subjects:
- kind: ServiceAccount
  name: emqx
  namespace: default
roleRef:
  kind: Role
  name: emqx
  apiGroup: rbac.authorization.k8s.io


