apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
    nodePort: 31883
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: mqttssl
  - name: mgmt
    port: 8081
    protocol: TCP
    targetPort: mgmt
    nodePort: 30081
  - name: ws
    port: 8083
    protocol: TCP
    targetPort: ws
    nodePort: 30083
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: wss
    nodePort: 30084
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: dashboard
    nodePort: 30003
