apiVersion: rbac.authorization.kubernetes.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: emqx
subjects:
- kind: ServiceAccount
  name: emqx
  namespace: default
  apiGroup: rbac.authorization.kubernetes.io
roleRef:
  kind: ClusterRole
  name: admi
  apiGroup: rbac.authorization.kubernetes.io


