apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-test
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nfs-test
  template:
    metadata:
      labels:
        app: nfs-test
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: nginx
        image: nginx:1.18.0
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: web
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
